### ISSUE TITLE
Cannot harvest orcas

### ISSUE THREAD

**Issue by Tylerguns12** [Jods-Its/Jods-Bountiful-Foraging#3]
When I go up to a ravaged or non ravaged orca I cannot harvest them.

**Comment by Jods-Its** [comment]
You do not harvest them like usual carcasses. Meat/Quarters spawn next to ravaged corpses. This might change in the future, but as of now you cannot.

**Comment by Tylerguns12** [comment]
Thanks good to know I've just been unlucky
